from rest_framework.response import Response
from rest_framework.views import APIView
from ..models import Note
from ..selializers import NoteSerializer
from django.db.models import Q
from rest_framework.status import *
from rest_framework.permissions import *
from drf_yasg.utils import swagger_auto_schema
from ..dto import NoteDTO